# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.apcension.com
title: Cloud Infrastructure Consulting
email: admin@apcension.com
author: Apcension, LLC
description: "Cloud consulting firm focused on implementing cutting edge cloud products built on kubernetes, mesos, marathon, docker, on-premise or cloud infrastructure."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/Apcension
  - title: github
    url: https://github.com/apcension-com/
  - title: linkedin
    url: 
